import pygame
# Variables used in game
# Screen
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
FONT_PATH = 'fonts/Montserrat-Regular.otf'
FONT_SIZE = 20
CAPTION = 'Ping Pong Game'
MID_LINE_START = [500,0]
MID_LINE_END = [500,600]
# Score
P1_SCORE_POS_X = 480
P1_SCORE_POS_Y = SCREEN_HEIGHT / 2
P2_SCORE_POS_X = 520
P2_SCORE_POS_Y = SCREEN_HEIGHT/ 2
# Players
PLAYER_WIDTH = 5
PLAYER_HEIGHT = 100
PLAYER_SPEED = 5
# Player One
PLAYER_ONE_POS_X = 2
PLAYER_ONE_POS_Y = SCREEN_HEIGHT / 2
# Player Two
PLAYER_TWO_POS_X = 998
PLAYER_TWO_POS_Y = SCREEN_HEIGHT / 2
# Ball
BALL_WIDTH = 10
BALL_HEIGHT = 10
BALL_INIT_POS_X = SCREEN_WIDTH / 2
BALL_INIT_POS_Y = SCREEN_HEIGHT / 2
BALL_SPEED = 7

# Colors
GREY = (133, 133, 133)
DARK_GREY = (61, 61, 61)
BG_COLOR = (15, 15, 15)